[db_connection]
host = "ep-snowy-bar-a5zv1qhw-pooler.us-east-2.aws.neon.tech"
port = "5432"
dbname = "neondb"
user = "neondb_owner"
password = "npg_vJSrcVfZ7N6a"
sslmode = "require"

[encryption]
key = "your-encryption-key-here"  # Generate with: `python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"`
